#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

arm_deployment_gate() {
  local readback
  if ! gh variable set "$DEPLOY_GATE" --body true >/dev/null 2>&1; then
    printf 'Deployment gate could not be armed. The first-deployment workflow was not dispatched.\n' >&2
    verified_disarm_deployment_gate
    return 1
  fi
  if ! readback=$(gh variable get "$DEPLOY_GATE" --json value --jq .value 2>/dev/null) || [[ "$readback" != "true" ]]; then
    printf 'Deployment gate could not be armed: exact true readback failed. Compensating to false.\n' >&2
    verified_disarm_deployment_gate
    return 1
  fi
  DEPLOY_GATE_STATE="true"
}

verified_disarm_deployment_gate() {
  local readback
  if ! gh variable set "$DEPLOY_GATE" --body false >/dev/null 2>&1 ||
    ! readback=$(gh variable get "$DEPLOY_GATE" --json value --jq .value 2>/dev/null) ||
    [[ "$readback" != "false" ]]; then
    DEPLOY_GATE_STATE="unknown"
    printf 'FAIL-CLOSED WARNING: repository variable %s could not verify false. Stop and inspect it before any main push or deployment attempt.\n' "$DEPLOY_GATE" >&2
    return 1
  fi
  DEPLOY_GATE_STATE="false"
}

compute_dist_digest() {
  local artifact_root="$1"
  (
    cd "$artifact_root"
    find dist -type f -print0 |
      LC_ALL=C sort -z |
      xargs -0 shasum -a 256 |
      shasum -a 256 |
      awk '{print $1}'
  )
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
CLOUDFLARE_TOKENS_URL="https://dash.cloudflare.com/profile/api-tokens"
GITHUB_ENVIRONMENT="portfolio-main-preview"
DEPLOY_GATE="PORTFOLIO_MAIN_PREVIEW_CUSTOM_DOMAIN_DEPLOY_ENABLED"
PR_URL=""
DEPLOY_GATE_STATE="unknown"
POST_MERGE_MAIN=false
TARGET_SHA=""
SUCCESSFUL_PUSH_RUN_ID=""
EXPECTED_DIST_DIGEST=""
TEMP_ROOT="${TMPDIR:-/tmp}"
TEMP_ROOT="${TEMP_ROOT%/}"
ARTIFACT_ROOT=""

cleanup_main_preview_secrets() {
  unset MAIN_PREVIEW_SESSION_SECRET OPENAI_PRODUCTION_KEY
  unset CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID
  if [[ -n "$ARTIFACT_ROOT" &&
    -d "$ARTIFACT_ROOT" &&
    "$ARTIFACT_ROOT" == "$TEMP_ROOT"/portfolio-main-preview.* ]]; then
    rm -rf -- "$ARTIFACT_ROOT"
  fi
}
trap cleanup_main_preview_secrets EXIT

for dependency in gh git node npx openssl shasum; do
  command -v "$dependency" >/dev/null 2>&1 || {
    printf '%s is required before running this setup.\n' "$dependency" >&2
    exit 1
  }
done

cd "$REPO_ROOT"
if [[ -n "${CONDUCTOR_WORKSPACE_NAME:-}" || -n "${CLAUDE_AGENT_SDK_VERSION:-}" ]]; then
  printf 'This wizard must run in Apple Terminal or iTerm outside Conductor.\n' >&2
  printf 'Conductor agent sessions deliberately use a GitHub token without Workflows permission.\n' >&2
  printf 'Run: cd %q && npm run setup:main-preview\n' "$REPO_ROOT" >&2
  exit 1
fi

CURRENT_BRANCH=$(git branch --show-current)
if [[ -z "$CURRENT_BRANCH" ]]; then
  printf 'Run this wizard from a prepared feature branch or an up-to-date main checkout.\n' >&2
  exit 1
fi
if [[ "$CURRENT_BRANCH" == "main" ]] && [[ -n "$(git status --porcelain)" ]]; then
  printf 'Post-merge activation requires a clean checkout. Commit, stash, or remove tracked and untracked changes before rerunning this wizard.\n' >&2
  exit 1
fi

banner "Permanent main preview setup"

stage "GitHub preflight and pull request"
if gh auth status >/dev/null 2>&1; then
  say "GitHub CLI is already authenticated; no login is needed."
else
  say "GitHub CLI needs authentication; opening its login flow."
  gh auth login
fi

if [[ "$CURRENT_BRANCH" == "main" ]]; then
  say "Checking that this checkout is the exact current origin/main commit."
  git fetch origin main:refs/remotes/origin/main
  LOCAL_HEAD_SHA=$(git rev-parse HEAD)
  ORIGIN_MAIN_SHA=$(git rev-parse origin/main)
  if [[ "$LOCAL_HEAD_SHA" != "$ORIGIN_MAIN_SHA" ]]; then
    printf 'Local HEAD (%s) does not equal fetched origin/main (%s).\n' "$LOCAL_HEAD_SHA" "$ORIGIN_MAIN_SHA" >&2
    printf 'Update the checkout to the exact merged main commit before activating it.\n' >&2
    exit 1
  fi
  POST_MERGE_MAIN=true
  TARGET_SHA="$ORIGIN_MAIN_SHA"
  say "Activation will target the successful main push for $TARGET_SHA."
else
  say "Publishing $CURRENT_BRANCH so GitHub can open the setup pull request."
  if ! git push -u origin HEAD; then
    printf 'GitHub rejected the push. Do not broaden the biv-agent App permissions.\n' >&2
    printf 'Confirm this is Apple Terminal or iTerm, then run gh auth refresh -h github.com -s workflow and rerun the wizard.\n' >&2
    exit 1
  fi
fi

REPOSITORY=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
if [[ "$POST_MERGE_MAIN" == "false" ]]; then
  if PR_URL=$(gh pr view --json url --jq .url 2>/dev/null); then
    say "Using the existing pull request: $PR_URL"
  else
    PR_URL=$(gh pr create \
      --base main \
      --title "Add the permanent main preview" \
      --body "Adds a permanent deployment of the latest tested main build on the apex, www, and Workers.dev hostnames. Deployment remains false-gated until the setup wizard explicitly arms it. Includes deterministic auth, Worker, and workflow coverage plus the activation and rollback packet.")
    say "Created pull request: $PR_URL"
  fi
fi

stage "Worker secrets"
say "The signing secret stays in memory and streams directly to Cloudflare."
ask_secret OPENAI_PRODUCTION_KEY "Paste the production OpenAI service-account key:"
say "Validating the OpenAI key before upload…"
printf '%s' "$OPENAI_PRODUCTION_KEY" | \
  node "$SCRIPT_DIR/portfolio-chat-setup-helper.mjs" validate-openai-key
MAIN_PREVIEW_SESSION_SECRET=$(openssl rand -base64 48)
if (( ${#MAIN_PREVIEW_SESSION_SECRET} < 32 )); then
  printf 'Could not generate a sufficiently long signing secret.\n' >&2
  exit 1
fi

warn "Uploading these secrets can create or update the dedicated Cloudflare Worker. Rotating the signing secret ends existing reviewer sessions."
if ! confirm "Upload the two encrypted secrets to bradley-portfolio-main-preview?"; then
  SKIPPED+=("Worker secret upload (rerun npm run setup:main-preview)")
  unset MAIN_PREVIEW_SESSION_SECRET OPENAI_PRODUCTION_KEY
else
  if ! npx wrangler whoami >/dev/null 2>&1; then
    say "Cloudflare needs authentication; opening its login flow."
    npx wrangler login
  fi
  printf '%s\n' "$MAIN_PREVIEW_SESSION_SECRET" | \
    npx wrangler secret put PORTFOLIO_MAIN_PREVIEW_SESSION_SECRET --config wrangler.main-preview.jsonc
  printf '%s\n' "$OPENAI_PRODUCTION_KEY" | \
    npx wrangler secret put OPENAI_API_KEY --config wrangler.main-preview.jsonc
  say "Cloudflare received both encrypted Worker secrets."
  unset MAIN_PREVIEW_SESSION_SECRET OPENAI_PRODUCTION_KEY
fi

stage "GitHub deployment environment"
say "Create a least-privilege Cloudflare token that can deploy Workers in the portfolio account."
open_url "$CLOUDFLARE_TOKENS_URL"
step "Create a Custom token with Account · Workers Scripts · Edit for the intended account only."
step "Add Zone · Workers Routes · Edit, scoped only to bradleyberkman.com."
step "Copy the account ID from the Cloudflare dashboard overview."
ask CLOUDFLARE_ACCOUNT_ID "Paste the 32-character Cloudflare account ID:"
ask_secret CLOUDFLARE_API_TOKEN "Paste the Cloudflare API token:"
if [[ ! "$CLOUDFLARE_ACCOUNT_ID" =~ ^[[:xdigit:]]{32}$ ]]; then
  printf 'The Cloudflare account ID must be 32 hexadecimal characters.\n' >&2
  exit 1
fi
if [[ -z "$CLOUDFLARE_API_TOKEN" ]]; then
  printf 'The Cloudflare API token cannot be empty.\n' >&2
  exit 1
fi

if confirm "Store these deployment credentials in the $GITHUB_ENVIRONMENT GitHub environment?"; then
  gh api --method PUT "repos/$REPOSITORY/environments/$GITHUB_ENVIRONMENT" >/dev/null
  printf '%s' "$CLOUDFLARE_API_TOKEN" | \
    gh secret set CLOUDFLARE_API_TOKEN --env "$GITHUB_ENVIRONMENT"
  printf '%s' "$CLOUDFLARE_ACCOUNT_ID" | \
    gh secret set CLOUDFLARE_ACCOUNT_ID --env "$GITHUB_ENVIRONMENT"
  WRITTEN_SECRET+=("$GITHUB_ENVIRONMENT/CLOUDFLARE_API_TOKEN")
  WRITTEN_SECRET+=("$GITHUB_ENVIRONMENT/CLOUDFLARE_ACCOUNT_ID")
  unset CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID

  if CURRENT_GATE=$(gh variable get "$DEPLOY_GATE" --json value --jq .value 2>/dev/null); then
    DEPLOY_GATE_STATE="$CURRENT_GATE"
    say "The existing deployment gate remains $DEPLOY_GATE_STATE."
  else
    set_var "$DEPLOY_GATE" false
    DEPLOY_GATE_STATE="false"
    say "Automatic deployment is disabled by default."
  fi
else
  SKIPPED+=("GitHub deployment environment credentials (rerun npm run setup:main-preview)")
  unset CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID
fi

if [[ "$DEPLOY_GATE_STATE" == "unknown" ]]; then
  DEPLOY_GATE_STATE=$(gh variable get "$DEPLOY_GATE" --json value --jq .value 2>/dev/null || printf 'false')
fi

open_url "https://github.com/$REPOSITORY/settings/environments"
step "Open $GITHUB_ENVIRONMENT and add the desired required reviewer before activation/deployment."
pause "Press Enter after reviewing the environment protection."

stage "Optional activation"
say "The current $DEPLOY_GATE value is $DEPLOY_GATE_STATE."
if [[ "$DEPLOY_GATE_STATE" == "true" ]]; then
  say "Automatic deployment is already armed; pressing Enter leaves it armed."
  ask ACTIVATION_CONFIRMATION "Type DISABLE to stop future main deployments, or press Enter to keep it armed:"
  if [[ "$ACTIVATION_CONFIRMATION" == "DISABLE" ]]; then
    set_var "$DEPLOY_GATE" false
    say "Automatic deployment is now disabled."
  else
    say "Automatic deployment remains armed."
  fi
else
  if [[ "$POST_MERGE_MAIN" == "true" ]]; then
    SUCCESSFUL_PUSH_RUN_ID=$(gh run list \
      --workflow ci.yml \
      --branch main \
      --commit "$TARGET_SHA" \
      --event push \
      --status success \
      --json databaseId \
      --jq '.[0].databaseId')
    if [[ -z "$SUCCESSFUL_PUSH_RUN_ID" ]]; then
      printf 'No successful ci.yml push run was found for main commit %s. Deployment remains disabled.\n' "$TARGET_SHA" >&2
      exit 1
    fi

    ARTIFACT_ROOT=$(mktemp -d "$TEMP_ROOT/portfolio-main-preview.XXXXXX")
    if ! gh run download "$SUCCESSFUL_PUSH_RUN_ID" \
      --repo "$REPOSITORY" \
      --name "portfolio-main-preview-$TARGET_SHA" \
      --dir "$ARTIFACT_ROOT/dist"; then
      printf 'Could not download the tested artifact from successful CI run %s. Deployment remains disabled.\n' "$SUCCESSFUL_PUSH_RUN_ID" >&2
      exit 1
    fi
    if [[ -z "$(find "$ARTIFACT_ROOT/dist" -type f -print -quit)" ]]; then
      printf 'The tested artifact from successful CI run %s was empty. Deployment remains disabled.\n' "$SUCCESSFUL_PUSH_RUN_ID" >&2
      exit 1
    fi
    EXPECTED_DIST_DIGEST=$(compute_dist_digest "$ARTIFACT_ROOT")
    say "Successful source CI run: $SUCCESSFUL_PUSH_RUN_ID"
    say "Exact main commit: $TARGET_SHA"
    say "Approved sorted dist SHA-256 digest: $EXPECTED_DIST_DIGEST"
    say "The manual first-deployment workflow will download this existing artifact and verify this digest without rebuilding it."
  fi

  say "Type ACTIVATE only if every successfully tested main push should update the live Worker."
  ask ACTIVATION_CONFIRMATION "Type ACTIVATE to arm deployment, or press Enter to leave it disabled:"
  if [[ "$ACTIVATION_CONFIRMATION" == "ACTIVATE" ]]; then
    if ! arm_deployment_gate; then
      exit 1
    fi
    if [[ "$POST_MERGE_MAIN" == "true" ]]; then
      if ! gh workflow run deploy-main-preview.yml \
        --repo "$REPOSITORY" \
        --ref main \
        --field "source_run_id=$SUCCESSFUL_PUSH_RUN_ID" \
        --field "source_sha=$TARGET_SHA" \
        --field "expected_dist_digest=$EXPECTED_DIST_DIGEST"; then
        printf 'Manual first-deployment workflow dispatch failed. Compensating the deployment gate to false.\n' >&2
        verified_disarm_deployment_gate
        exit 1
      fi
      warn "Deployment is armed. The digest-bound first-deployment workflow was dispatched for CI run $SUCCESSFUL_PUSH_RUN_ID and $TARGET_SHA."
    else
      warn "Deployment is armed. Review and merge the pull request to trigger the protected main deployment."
    fi
  else
    say "Deployment remains disabled. Re-run this wizard when you are ready to activate it."
  fi
fi

if [[ -n "$PR_URL" ]]; then
  open_url "$PR_URL"
fi
finish
if [[ -n "$PR_URL" ]]; then
  note "Pull request: $PR_URL"
elif [[ -n "$SUCCESSFUL_PUSH_RUN_ID" ]]; then
  note "Source CI workflow: https://github.com/$REPOSITORY/actions/runs/$SUCCESSFUL_PUSH_RUN_ID"
fi
note "No signing secret, provider key, or Cloudflare token was written to this repository or shell history."
