#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
CLOUDFLARE_TOKENS_URL="https://dash.cloudflare.com/profile/api-tokens"
CLARITY_SETTINGS_URL="https://clarity.microsoft.com/projects/view/yatoiqtrjm/settings"
WIDGET_NAME="portfolio-chat"
WIDGET_DOMAINS='["bradleyberkman.com","www.bradleyberkman.com"]'
GITHUB_VARIABLE="PORTFOLIO_CHAT_TURNSTILE_SITE_KEY"
NOTES_FILE="$REPO_ROOT/.context/turnstile-clarity-setup.md"
API_BASE="https://api.cloudflare.com/client/v4"
TURNSTILE_SITE_KEY=""
SITE_KEY_PUBLISHED=0
WORKER_SECRET_UPLOADED=0
IDENTIFIER_SECRET_UPLOADED=0
CLARITY_COOKIE_CONSENT=""
KEEP_EXISTING_SECRET=0

cleanup_turnstile_secrets() {
  unset CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID TURNSTILE_SECRET_KEY
  unset PORTFOLIO_CHAT_IDENTIFIER_SECRET
}
trap cleanup_turnstile_secrets EXIT

for dependency in curl gh node npx openssl; do
  command -v "$dependency" >/dev/null 2>&1 || {
    printf '%s is required before running this setup.\n' "$dependency" >&2
    exit 1
  }
done

cd "$REPO_ROOT"
if [[ -n "${CONDUCTOR_WORKSPACE_NAME:-}" || -n "${CLAUDE_AGENT_SDK_VERSION:-}" ]]; then
  printf 'This wizard must run in Apple Terminal or iTerm outside Conductor.\n' >&2
  printf 'It handles a live Cloudflare admin token and writes repository settings, which agent sessions deliberately cannot do.\n' >&2
  printf 'Run: cd %q && npm run setup:turnstile\n' "$REPO_ROOT" >&2
  exit 1
fi

# Reads one field out of a Cloudflare API response on stdin. Fails loudly with
# the API's own error messages rather than a silent empty value.
cloudflare_field() {
  CF_FIELD="$1" node -e '
    let raw = "";
    process.stdin.on("data", (chunk) => (raw += chunk));
    process.stdin.on("end", () => {
      let body;
      try {
        body = JSON.parse(raw);
      } catch {
        process.stderr.write("Cloudflare returned a non-JSON response.\n");
        process.exit(1);
      }
      if (!body.success) {
        const errors = (body.errors ?? []).map((e) => `${e.code}: ${e.message}`);
        process.stderr.write(`Cloudflare rejected the request. ${errors.join("; ")}\n`);
        process.exit(1);
      }
      const value = process.env.CF_FIELD
        .split(".")
        .reduce((node, key) => (node == null ? node : node[key]), body.result);
      if (value === undefined || value === null || value === "") {
        process.stderr.write(`Cloudflare response had no ${process.env.CF_FIELD}.\n`);
        process.exit(1);
      }
      process.stdout.write(String(value));
    });
  '
}

# Lists the accounts this token can see, as "id<TAB>name" lines. The token may
# be scoped too narrowly to enumerate accounts, so an empty result is normal
# and just means the human types the ID in.
list_accounts() {
  curl -sS -X GET "$API_BASE/accounts" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" 2>/dev/null |
    node -e '
      let raw = "";
      process.stdin.on("data", (chunk) => (raw += chunk));
      process.stdin.on("end", () => {
        try {
          const body = JSON.parse(raw);
          if (!body.success) return;
          for (const account of body.result ?? []) {
            process.stdout.write(`${account.id}\t${account.name}\n`);
          }
        } catch {
          /* an unreadable list is not an error here */
        }
      });
    ' 2>/dev/null || printf ''
}

# The sitekey of an existing widget with our name, or empty. Never fails the
# run: an unreadable list just means we create a new widget.
existing_widget_sitekey() {
  curl -sS -X GET \
    "$API_BASE/accounts/$CLOUDFLARE_ACCOUNT_ID/challenges/widgets" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" 2>/dev/null |
    WIDGET_NAME="$WIDGET_NAME" node -e '
      let raw = "";
      process.stdin.on("data", (chunk) => (raw += chunk));
      process.stdin.on("end", () => {
        try {
          const body = JSON.parse(raw);
          const match = (body.result ?? []).find(
            (widget) => widget.name === process.env.WIDGET_NAME,
          );
          process.stdout.write(match?.sitekey ?? "");
        } catch {
          process.stdout.write("");
        }
      });
    ' 2>/dev/null || printf ''
}

banner "Portfolio chat Turnstile setup"

# ──────────────────────────────────────────────────────────────────────────
stage "Cloudflare credentials"
say "The token stays in this shell's memory and is never written to disk."
say "It needs the Turnstile Sites Write permission on your account."
open_url "$CLOUDFLARE_TOKENS_URL"
step "Use an existing token with Turnstile Sites Write, or Create Token →"
step "  Custom token → Permissions: Account · Turnstile · Edit."
step "Copy the token."
ask_secret CLOUDFLARE_API_TOKEN "Paste the Cloudflare API token:"
if [[ -z "$CLOUDFLARE_API_TOKEN" ]]; then
  printf 'The API token is required.\n' >&2
  exit 1
fi

say "Looking up the accounts this token can see…"
ACCOUNTS=$(list_accounts)
ACCOUNT_COUNT=$(printf '%s' "$ACCOUNTS" | grep -c . || true)
if [[ "$ACCOUNT_COUNT" -eq 1 ]]; then
  CLOUDFLARE_ACCOUNT_ID=$(printf '%s' "$ACCOUNTS" | cut -f1)
  say "Found one account: $(printf '%s' "$ACCOUNTS" | cut -f2) ($CLOUDFLARE_ACCOUNT_ID)"
elif [[ "$ACCOUNT_COUNT" -gt 1 ]]; then
  say "This token can see $ACCOUNT_COUNT accounts:"
  printf '%s\n' "$ACCOUNTS" | while IFS=$'\t' read -r id name; do
    step "$name — $id"
  done
  ask CLOUDFLARE_ACCOUNT_ID "Paste the account ID to use:"
else
  note "The token cannot enumerate accounts, which is fine for a narrow scope."
  note "Find the ID by clicking Manage account in the dashboard sidebar: it is"
  note "the 32-character string in the URL. Or run: npx wrangler whoami"
  ask CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare account ID:"
fi
if [[ ! "$CLOUDFLARE_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]]; then
  printf 'That does not look like a Cloudflare account ID (32 hex characters).\n' >&2
  exit 1
fi
say "Checking the token against the Turnstile API…"
curl -sS -X GET \
  "$API_BASE/accounts/$CLOUDFLARE_ACCOUNT_ID/challenges/widgets" \
  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" |
  node -e '
    let raw = "";
    process.stdin.on("data", (chunk) => (raw += chunk));
    process.stdin.on("end", () => {
      let body;
      try {
        body = JSON.parse(raw);
      } catch {
        process.stderr.write("Cloudflare returned a non-JSON response.\n");
        process.exit(1);
      }
      if (!body.success) {
        const errors = (body.errors ?? []).map((e) => `${e.code}: ${e.message}`);
        process.stderr.write(
          `Token check failed. ${errors.join("; ") || "Check the account ID and the Turnstile Sites Write permission."}\n`,
        );
        process.exit(1);
      }
    });
  '
say "Token accepted for this account."

# ──────────────────────────────────────────────────────────────────────────
stage "Create the Turnstile widget"
say "Widget name: $WIDGET_NAME"
say "Domains:     bradleyberkman.com, www.bradleyberkman.com"
say "Mode:        managed"
note "Both hostnames matter: the Worker rejects a token whose hostname does not"
note "match the request, so a widget missing www fails every question there."

EXISTING_SITE_KEY=$(existing_widget_sitekey)
if [[ -n "$EXISTING_SITE_KEY" ]]; then
  warn "A widget named $WIDGET_NAME already exists (site key $EXISTING_SITE_KEY)."
  say "Cloudflare only reveals a secret at creation, so reusing it means rotating."
  if confirm "Rotate this widget's secret now? The old secret stops working."; then
    TURNSTILE_SITE_KEY="$EXISTING_SITE_KEY"
    TURNSTILE_SECRET_KEY=$(curl -sS -X POST \
      "$API_BASE/accounts/$CLOUDFLARE_ACCOUNT_ID/challenges/widgets/$TURNSTILE_SITE_KEY/rotate_secret" \
      -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
      -H "Content-Type: application/json" \
      --data '{"invalidate_immediately":true}' | cloudflare_field secret)
    say "Secret rotated."
  else
    say "Keeping the existing widget and its current secret."
    TURNSTILE_SITE_KEY="$EXISTING_SITE_KEY"
    KEEP_EXISTING_SECRET=1
  fi
else
  if ! confirm "Create the $WIDGET_NAME widget on this Cloudflare account?"; then
    printf 'No widget created. Re-run when ready.\n' >&2
    exit 1
  fi
  WIDGET_RESPONSE=$(curl -sS -X POST \
    "$API_BASE/accounts/$CLOUDFLARE_ACCOUNT_ID/challenges/widgets" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    -H "Content-Type: application/json" \
    --data "{\"name\":\"$WIDGET_NAME\",\"domains\":$WIDGET_DOMAINS,\"mode\":\"managed\"}")
  TURNSTILE_SITE_KEY=$(printf '%s' "$WIDGET_RESPONSE" | cloudflare_field sitekey)
  TURNSTILE_SECRET_KEY=$(printf '%s' "$WIDGET_RESPONSE" | cloudflare_field secret)
  unset WIDGET_RESPONSE
  say "Widget created."
fi
say "Site key (public): $TURNSTILE_SITE_KEY"
note "The secret key is held in memory only and is never printed or written to disk."
pause "Press Enter to publish these where the build and the Worker read them."

# ──────────────────────────────────────────────────────────────────────────
stage "Publish the site key to GitHub Actions"
say "The site key is compiled into the client bundle, so CI needs it at build time."
say "It is public by design, so it is a repository variable, not a secret."
if gh auth status >/dev/null 2>&1; then
  say "GitHub CLI is already authenticated."
else
  say "GitHub CLI needs authentication; opening its login flow."
  gh auth login
fi
if gh variable set "$GITHUB_VARIABLE" --body "$TURNSTILE_SITE_KEY"; then
  SITE_KEY_PUBLISHED=1
  say "Set repository variable $GITHUB_VARIABLE."
else
  SKIPPED+=("GitHub variable $GITHUB_VARIABLE (gh variable set $GITHUB_VARIABLE --body $TURNSTILE_SITE_KEY)")
  warn "Could not set the repository variable; the command above does it by hand."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Upload the secret key to the Worker"
say "The Worker verifies every challenge token with this secret."
warn "Uploading a secret creates and deploys a new Worker version immediately."
if ((KEEP_EXISTING_SECRET)); then
  say "Keeping the widget's existing secret, so there is nothing to upload."
  note "The Worker already holds it from the run that created the widget."
  WORKER_SECRET_UPLOADED=1
elif confirm "Upload TURNSTILE_SECRET_KEY to bradley-portfolio-main-preview?"; then
  if ! npx wrangler whoami >/dev/null 2>&1; then
    say "Cloudflare needs authentication; opening its login flow."
    npx wrangler login
  fi
  printf '%s\n' "$TURNSTILE_SECRET_KEY" |
    npx wrangler secret put TURNSTILE_SECRET_KEY --config wrangler.main-preview.jsonc
  WORKER_SECRET_UPLOADED=1
  say "Worker secret uploaded."
else
  SKIPPED+=("Worker secret TURNSTILE_SECRET_KEY (rerun npm run setup:turnstile and rotate)")
  warn "Skipped. The secret is discarded when this wizard exits, so a later run must rotate it."
fi
unset TURNSTILE_SECRET_KEY

# ──────────────────────────────────────────────────────────────────────────
stage "Generate the chat identifier secret"
say "The third control the public guard needs, alongside the challenge and the"
say "route limiter. The runtime HMACs Cloudflare's connecting IP with it before"
say "using the result as a limiter key and as OpenAI's safety_identifier, so a"
say "raw IP is never forwarded or logged."
warn "Without it the guard returns 503 for every question once the challenge is"
warn "required. It has no dashboard: this generates it locally."
if npx wrangler secret list --config wrangler.main-preview.jsonc 2>/dev/null |
  grep -q PORTFOLIO_CHAT_IDENTIFIER_SECRET; then
  say "The Worker already holds PORTFOLIO_CHAT_IDENTIFIER_SECRET."
  note "Rotating it only changes future pseudonyms; it breaks nothing."
  IDENTIFIER_SECRET_UPLOADED=1
  if ! confirm "Rotate it anyway?"; then
    say "Keeping the existing identifier secret."
  else
    IDENTIFIER_SECRET_UPLOADED=0
  fi
fi
if ((IDENTIFIER_SECRET_UPLOADED == 0)); then
  PORTFOLIO_CHAT_IDENTIFIER_SECRET=$(openssl rand -base64 48)
  if (( ${#PORTFOLIO_CHAT_IDENTIFIER_SECRET} < 32 )); then
    printf 'Could not generate a sufficiently long identifier secret.\n' >&2
    exit 1
  fi
  if confirm "Upload PORTFOLIO_CHAT_IDENTIFIER_SECRET to bradley-portfolio-main-preview?"; then
    printf '%s\n' "$PORTFOLIO_CHAT_IDENTIFIER_SECRET" |
      npx wrangler secret put PORTFOLIO_CHAT_IDENTIFIER_SECRET --config wrangler.main-preview.jsonc
    IDENTIFIER_SECRET_UPLOADED=1
    say "Identifier secret uploaded."
  else
    SKIPPED+=("Worker secret PORTFOLIO_CHAT_IDENTIFIER_SECRET (rerun npm run setup:turnstile)")
    warn "Skipped. The challenge cannot be required until this exists."
  fi
  unset PORTFOLIO_CHAT_IDENTIFIER_SECRET
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Read Clarity's cookie consent setting"
say "One dashboard value decides what Clarity stores on a first visit, before"
say "anyone has expressed a preference. It cannot be read from an API key."
open_url "$CLARITY_SETTINGS_URL"
step "Open project yatoiqtrjm → Settings → Setup (not the Overview page)."
step "Scroll to Advanced settings → Cookies and turn that toggle OFF."
step "Leave Bot detection on."
warn "The toggle reads the other way round: Cookies OFF is what enables"
warn "Consent Mode. ON means Clarity sets its own cookies by default."
note "Recommended: OFF. Clarity then stays cookieless until it receives an"
note "explicit granted, which is exactly what this site sends and only when a"
note "visitor has saved an opt-in. That keeps the reviewed /privacy notice"
note "accurate as written, with no copy change needed. Clarity already enforces"
note "this for EEA, UK and Swiss visitors since 31 Oct 2025."
note "Cost: unlinked multi-page sessions for visitors who have not opted in."
note "Small here, since the portfolio is one document with hash routes and the"
note "attention signals are per content, not per journey."
ask CLARITY_COOKIE_CONSENT "The Cookies toggle is now? (changed-to-off/already-off/left-on):"
mkdir -p "$(dirname "$NOTES_FILE")"
{
  printf '# Turnstile and Clarity setup\n\n'
  printf 'Recorded by scripts/setup-portfolio-turnstile.sh on %s.\n\n' "$(date -u '+%Y-%m-%d %H:%M UTC')"
  printf -- '- Turnstile site key: `%s`\n' "$TURNSTILE_SITE_KEY"
  printf -- '- GitHub variable %s published: %s\n' "$GITHUB_VARIABLE" \
    "$( ((SITE_KEY_PUBLISHED)) && printf 'yes' || printf 'no')"
  printf -- '- Worker secret TURNSTILE_SECRET_KEY uploaded: %s\n' \
    "$( ((WORKER_SECRET_UPLOADED)) && printf 'yes' || printf 'no')"
  printf -- '- Worker secret PORTFOLIO_CHAT_IDENTIFIER_SECRET uploaded: %s\n' \
    "$( ((IDENTIFIER_SECRET_UPLOADED)) && printf 'yes' || printf 'no')"
  printf -- '- Clarity Settings > Setup > Advanced settings > Cookies toggle: %s\n' "$CLARITY_COOKIE_CONSENT"
  printf -- '  (off = Consent Mode on = no cookies until an explicit granted)\n'
} > "$NOTES_FILE"
say "Recorded to .context/turnstile-clarity-setup.md for the agent session."

finish
note "Site key: $TURNSTILE_SITE_KEY"
if ((SITE_KEY_PUBLISHED)) && ((WORKER_SECRET_UPLOADED)) && ((IDENTIFIER_SECRET_UPLOADED)); then
  note "All three controls are in place. Tell the agent session to flip"
  note "PORTFOLIO_CHAT_TURNSTILE_REQUIRED to true and add TURNSTILE_SECRET_KEY"
  note "to the required secrets in wrangler.main-preview.jsonc."
  warn "Do not flip that flag before this Worker secret is live: the guard"
  warn "deliberately returns 503 for every question when the flag is on"
  warn "without the secret."
else
  warn "The flag must stay false until all three above are done."
fi
